### ISSUE TITLE
Install Error - CalendarView vs calendar-view vs `from calendar_view import Calendar`

### ISSUE THREAD

**Issue by datatalking** [sakhnevych/calendar-view#16] opened 2023-05-27 15:58 UTC
@sakhnevych We liked the look of your package and tried to run it but getting errors.

why are there threee different names with the import, why can't we choose one of those as I can't install it as written. Your repo is `CalendarView` pypi lists it as `calendar-view` and to further complicate it you import it as `calendar-view`

Why triple complicate the naming schema?

How do we get it running with these errors.

<img width="1399" alt="Screen Shot 2023-05-27 at 8 55 28 AM" src="https://github.com/sakhnevych/CalendarView/assets/11813209/9ca0d4d2-3cb2-4c42-bade-41fe9cc92d1a">
<img width="742" alt="Screen Shot 2023-05-27 at 8 54 31 AM" src="https://github.com/sakhnevych/CalendarView/assets/11813209/2fca4f18-a718-4403-b305-7fa4c17dd965">
<img width="876" alt="Screen Shot 2023-05-27 at 8 48 17 AM" src="https://github.com/sakhnevych/CalendarView/assets/11813209/ea3e03ff-0540-4627-83bb-7f543f05ced1">

**Comment by datatalking** [comment] 2023-05-27 16:00
@sakhnevych  Would you accept a PR if I updated the setup.py and elsewhere to change the python package to be pythonic and match the repo as in `[CalendarView](https://github.com/sakhnevych/CalendarView)`

**Comment by datatalking** [comment] 2023-05-27 16:16
I've tried to import this four different ways and even tried to pip install it directly from your repo including the egg since its installing in a usually bulletproof Jupyternotebook but still no avail.

LMK if you would accept a renamed PR, or how do you get it installed?
```
Collecting CalendarView
  Cloning https://github.com/sakhnevych/CalendarView.git to /private/var/folders/v0/7gtj3bhx74z6w7kx78fhqlmm0000gn/T/pip-install-ivs7d13q/calendarview_ad6d0c6a6c394d8b9a47ef67b6eb361f
  Running command git clone --filter=blob:none --quiet https://github.com/sakhnevych/CalendarView.git /private/var/folders/v0/7gtj3bhx74z6w7kx78fhqlmm0000gn/T/pip-install-ivs7d13q/calendarview_ad6d0c6a6c394d8b9a47ef67b6eb361f
  Resolved https://github.com/sakhnevych/CalendarView.git to commit 0a636604df91cc21f92158316ba8e05e0c1af799
  Preparing metadata (setup.py) ... [?25ldone
[33m  WARNING: Generating metadata for package CalendarView produced metadata for project name calendar-view. Fix your #egg=CalendarView fragments.[0m[33m
[0m[?25hDiscarding [4;34mgit+https://github.com/sakhnevych/CalendarView.git#egg=CalendarView[0m: [33mRequested calendar-view from git+https://github.com/sakhnevych/CalendarView.git#egg=CalendarView has inconsistent name: expected 'calendarview', but metadata has 'calendar-view'[0m
[31mERROR: Could not find a version that satisfies the requirement calendarview (unavailable) (from versions: none)[0m[31m
[0m[31mERROR: No matching distribution found for calendarview (unavailable)[0m[31m
[0m
```
<img width="810" alt="Screen Shot 2023-05-27 at 9 14 31 AM" src="https://github.com/sakhnevych/CalendarView/assets/11813209/155c6a97-4d8e-490c-b43b-8f6ce59d82c3">

**Comment by sakhnevych** [comment] 2023-05-27 19:25
Hi @datatalking. Thanks for reporting the bug. I agree that the naming could be confusing.
Let me see if I can make the naming changes backwards compatible.

**Comment by sakhnevych** [comment] 2023-05-27 20:06
According to https://pep8.org/#package-and-module-names, the preferred package name is `calendarview` or `calendar_view`.

After the investigation, I found the AWS CDK example https://pypi.org/project/aws-cdk.aws-supportapp/ that uses 2 namings:
- `aws-cdk.aws-supportapp` for the library name
- `aws_cdk.aws_supportapp` for the package name

Google library https://pypi.org/project/google-cloud-aiplatform/ use different naming:
- `google-cloud-aiplatform` for the library name
- `from google.cloud import aiplatform` for the packages

As far as I can see, 2 different names are acceptable, but 3 are not a good idea.

I believe the best option will be to rename the GitHub repository. But I need to make a release to publish documentation.

**Comment by sakhnevych** [comment] 2023-05-27 20:08
@datatalking , do you think the repository `https://github.com/sakhnevych/calendar-view` should work for you?

This installation command without the last parameter `#egg=CalendarView` works for me:
```
pip install git+https://github.com/sakhnevych/CalendarView.git
```

So I am not sure so far why the installation fails for you.

**Comment by sakhnevych** [comment] 2023-06-08 20:44
The repository is renamed to `calendar-view`. Thank you for opening the ticket.

I haven't received a message from you in this thread, so I'm closing the issue. Please feel free to reopen it or create a new one if something is wrong.

**Closed by sakhnevych** 2023-06-08 20:44 UTC

**Comment by datatalking** [comment] 2023-10-05 21:40
I wanted to revisit this as I find it's an ongoing issue, I'm facing while updating old 3.7 code to 3.9.

Since PEP8 rules recommend specific naming schemas for a package is called 'calendar-view'... but your documentation shows the import as being 'calendar_view'. I don't have a preference in how this should work I'm just not understanding how we are supposed to install it with one name 'calendar-view' but on import that doesn't work, 'calendar_view' does.

```
from calendar_view.calendar import Calendar
from calendar_view.config import style
from calendar_view.core import data
from calendar_view.core.event import Event
```

When I tell PyCharm to import your package as documented (which I need to understand) it generates an error.

<img width="963" alt="Screen Shot 2023-10-05 at 2 35 45 PM" src="https://github.com/sakhnevych/calendar-view/assets/11813209/5627d066-a327-4f8b-b925-f6dd9cb20123">

**Comment by sakhnevych** [comment] 2023-10-08 20:00
Python doesn't allow package names with the dash `-`.

We install the application using the PyPi name `calendar-view`. But the structure of the library can have a completely different name. Now it is `calendar_view`.

Sorry, but I can't rename the package name because Python doesn't support that. And I cannot rename the PyPi library name because that would break the code for those who are already using it.

**Comment by sakhnevych** [comment] 2023-10-08 20:03
I started the project from scratch, using the code you provided in the screenshot. I could not reproduce the issue.
<img width="1023" alt="Screenshot 2023-10-08 at 23 00 52" src="https://github.com/sakhnevych/calendar-view/assets/2226541/aac44e6c-e179-483b-94bf-3f2e5666e972">

Please help me reproduce it by providing the link to the steps to reproduce it.
